### ISSUE TITLE
Support Resource Owner Password Grants

### ISSUE THREAD

**Issue by ErikGrimes** [dart-lang/oauth2#14]
Support resource owner password grants.

**Comment by ErikGrimes** [comment]
I need to do this for one of my own projects.  I'm happy to submit a pull request.  The non-redirection flows are different than the redirection flows, so it might feel a bit kludgy to users.  Would you be open to some changes to make the library experience more unified?

**Comment by nex3** [comment]
What API changes are you envisioning?

**Comment by ErikGrimes** [comment]
I haven't spent too much time on it, but something along the lines of this seems like it might be reasonable:

```
/* resource owner password flow */

var flow = new ResourceOwnerPasswordFlow(authorizationEndpoint);

var await credentials = flow.execute(
'username', 
'password', 
client_id: 'client_id',
client_secret: 'client_secret'
scope: ['all'],
httpClient: httpClient); 

client = new Client(credentials);

/* base authorization code flow with interaction hooks */
var flow = new AuthorizationCodeFlow(
 authorizationEndpoint, 
 redirectUrl, // the url where the authorization server should redirect the user agent when authorization is complete
 responseHook: getResponse, // hook for getting the authorization response
 redirectHook: redirectUserAgent, // hook for redirecting the browser
 basicAuth: true
);

var await credentials flow.execute(
 client_id,
 client_secret: client_secret,
 scope: ['all'],
 state: 'state',
 httpClient: httpClient);
 
client = new Client(credentials);

```

**Comment by nex3** [comment]
I don't understand what the `AuthorizationCodeFlow` is doing there; I don't see any reference in [the spec](http://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-4.3) to needing any sort of redirection or browser interaction of any kind for a resource owner password credentials grant.

There's no state involved in this grant, so I'd probably expose it as a top-level method:

```dart
Future<Client> resourceOwnerPasswordCredentialsGrant(
    Uri authorizationEndpoint,
    String username,
    String password,
    {String identifier,
    String secret,
    List<String> scopes,
    http.Client httpClient});
```

I don't think this would require any changes to the existing API.

**Comment by ErikGrimes** [comment]
I should have been more clear. The AuthorizationCodeFlow is there to show one approach
to providing a common look and feel for the various OAuth flows. I could add a top level 
function for the resource owner password flow, but that would result in two distinct styles.
Not the end of the world, but it's surprising as a user and surprises consume brain cycles :)

Should I put the effort into proposed changes for a common look and feel or would you prefer I just add 
a top level function?

**Comment by nex3** [comment]
I'd rather have each flow work as naturally as possible in and of itself than have a lot of commonality between them. As long as they all spit out a `Client` at the end, I think that's consistent enough.

**Comment by ErikGrimes** [comment]
I don't think working naturally is opposed to a common look and feel in this case.  For example, this is implicit grant as a top level function, some parts omitted for brevity:

```
typedef Future<Map<String, String>> GetResponse();
typedef Future<Void> RedirectUserAgent(Uri authorizationUrl) ;

Future<Client> implicitGrant(
    Uri authorizationEndpoint,
    String clientId,
    String clientSecret,
    {
    RedirectUserAgent redirectUserAgent,
    GetResponse getResponse
}) async {
...
  await redirectUserAgent(url);
  var response = await getResponse();
  return _handleAuthorizationResponse(response);
}
```

I like the way this encapsulates the users responsibilities for making the flow work directly into the function call.  This implementation also tracks the spec very nicely.    

Thoughts? I'm considering a pull request for #5 based off this.

**Comment by nex3** [comment]
For flows with state, I want to stick with classes. Although requiring methods to be called in a certain sequence isn't ideal, it leaves room for more API flexibility (e.g. the ability to choose between `AuthorizationCodeGrant.handleAuthorizationResponse` and `AuthorizationCodeGrant.handleAuthorizationCode`) and it doesn't encourage users to write cumbersomely large anonymous functions.
