### ISSUE TITLE
Allow more content types for authorization response

### ISSUE THREAD

**Issue by tejainece** [dart-lang/oauth2#18]
Right now, the authorization response is assumed to be always "application/json". But this makes it non-compliant with facebook's response.

On success:
returns "text/plain" with response in multipart form data like response.

On Failure:
returns "text/javascript" with Json object as response.

Is it ok, if i submit a pull request that handles this acoording to whats in the "content-type" of the response?

**Comment by thosakwe** [comment]
Check out the changes in https://github.com/dart-lang/oauth2/pull/20.

You can provide a custom `getParameters` function now.
