### ISSUE TITLE
TypeError on failed auth response

### ISSUE THREAD

**Issue by kibantony** [dart-lang/oauth2#27]
Attempting a client.get with known bad tokens, I see the following error:
```
type 'List<dynamic>' is not a subtype of type 'List<AuthenticationChallenge>' where
I/flutter (21237):   List is from dart:core
I/flutter (21237):   List is from dart:core
I/flutter (21237):   AuthenticationChallenge is from package:http_parser/src/authentication_challenge.dart
I
I/flutter (21237): #0      AuthenticationChallenge.parseHeader (package:http_parser/src/authentication_challenge.dart:37:12)
I/flutter (21237): #1      Client.send (package:oauth2/src/client.dart:117:12)
I/flutter (21237): <asynchronous suspension>
I/flutter (21237): #2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:171:38)
I/flutter (21237): <asynchronous suspension>
I/flutter (21237): #3      BaseClient.get (package:http/src/base_client.dart:34:5)
```

# Flutter Doctor
[✓] Flutter (Channel beta, v0.3.1, on Mac OS X 10.12.6 16G1314, locale en-US)
    • Flutter version 0.3.1 at /Users/tony/afero/flutter
    • Framework revision 12bbaba9ae (12 days ago), 2018-04-19 23:36:15 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/tony/Library/Android/sdk
    • Android NDK at /Users/tony/Library/Android/sdk/ndk-bundle
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.4.0

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 24.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!

**Comment by nex3** [comment]
I believe this is an issue with `http_parser` that got fixed in https://github.com/dart-lang/http_parser/commit/e562446dbd552734239e6f51e4d5859b6f24a46e, but was never released. I'll see about cutting a release.

**Comment by nex3** [comment]
This should be fixed now.

**Comment by kibantony** [comment]
Thanks Natalie! I'll check it out.
