### ISSUE TITLE
Add flow for refresh token usage

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/oauth2#3]

**Comment by nex3** [comment]
Can you link to the portion of the spec that defines this flow?

**Comment by stevenroose** [comment]
The only explicit reference I can find is the image on [page 11](https://tools.ietf.org/html/rfc6749#page-11). Steps G and H.

**Comment by nex3** [comment]
From the spec:

> The client authentication requirements are based on the client type and on the authorization server policies.

It sounds like there's not a single unified way to do this that will work for all flows.
