### ISSUE TITLE
resourceOwnerPasswordGrant doesn't support a different tokenEndpoint

### ISSUE THREAD

**Issue by PizzaBrandon** [dart-lang/oauth2#30]
Presently `resourceOwnerPasswordGrant` will save the `authorizationEndpoint` as the `tokenEndpoint` in the saved credentials and doesn't allow for a unique endpoint for auth vs tokens. Is this intended or a side-effect of reusing the exiting structure? Would you be open to a PR to allow an optional `tokenEndpoint` to be provided?

**Comment by nex3** [comment]
According to the OAuth2 spec, the [Resource Owner Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3) makes a request to the token endpoint:

>    (B)  The client requests an access token from the authorization
>        server's token endpoint by including the credentials received
>        from the resource owner.

And the [Refreshing an Access Token flow](https://tools.ietf.org/html/rfc6749#section-6) does as well:

>    If the authorization server issued a refresh token to the client, the
>    client makes a refresh request to the token endpoint by adding the
>    following parameters using the "application/x-www-form-urlencoded"
>    format per Appendix B with a character encoding of UTF-8 in the HTTP
>    request entity-body:

It does seem like the parameter name `authorizationEndpoint` is inaccurate and should probably be changed to `tokenEndpoint`.

Do you have a server that treats these endpoints differently? There is precedent in this package for adding support for non-standard implementations of the protocol.

**Comment by PizzaBrandon** [comment]
This appears to be a misunderstanding of the spec on my part, then. I'm actually implementing my own oauth2 server (crazy, I know) in front of my API in order to communicate with the app I'm building. I have separate auth and refresh endpoints (it made it easier for validation), but the spec says that is incorrect. Thank you for the quick response and verification!

Closing.
