### ISSUE TITLE
Example app showing this being used?

### ISSUE THREAD

**Issue by Jeremywhiteley** [dart-lang/oauth2#31]
Do you haver a sample flutter app that shows this being used?   This would be very helpful.

**Comment by thosakwe** [comment]
I don't know if the example necessary needs to be for Flutter, since this library doesn't require it, and can be used on other platforms.

But I'd assume you could have a widget something like this pseudo-code:

```dart
class Foo extends StatefulWidget {
  @override
  State createState() => new _FooState();
}

class _FooState extends State<Foo> {
  oauth2.AuthorizationCodeGrant grant;
  oauth2.Client client;

  @override
  void initState() {
     grant = new oauth2.AuthorizationCodeGrant(...);
     
     // Say you're using uni_links or a similar plug-in...
     // Note: dispose of this Stream subscription in `deactivate`.
     theUniLinksCallback.listen((Uri uri) {
       var client =
        await grant.handleAuthorizationResponse(req.uri.queryParameters);

      setState(() {
         this.client = client;     
      });
    });
  }

  void onClick() {
    // Launch OAuth popup
    var redirect = Uri.parse('myapp://callback');
    grant.getAuthorizationUrl(redirect).then((url) {
      launch(url);
    });
   }

   @override
    Widget build(BuildContext context) { ... }
}
```

**Comment by jonasfj** [comment]
If anyone wants to write up a Flutter sample we can throw in the `example/` folder I would happy to accept a PR... just make it small :)

**Comment by emiltsang** [comment]
Can I have a detailed explanation on how to do with "theUniLinksCallback"?
I am quite confused on that part.
Thank you.

**Comment by thosakwe** [comment]
Your best bet is their docs: https://github.com/avioli/uni_links

**Comment by Alacon** [comment]
Thanks for the example.

However, it´s not completed and I´m to new to Flutter and Dart to be able to get this to work.

Is there anyone who can create a more complete example?
Would be much appreciated.

Thank you
