### ISSUE TITLE
resuming flow after redirect

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/oauth2#39]
Hi, I'm having difficulty implementing facebook authentication with this library. 

After I create an instance of AuthorizationCodeGrant I then redirect the users to the .getAuthorizationUrl(). When they eventually land back on my app I need call .handleAuthorizationResponse() on the grant object. But as the app has reinitialised I have to recreate the grant object and this isn’t working, I think because it’s not the same grant object that generated the redirect url? Do I need to serialize and store the original grant object for when the user returns back?

The documentation shows this:
```dart
  // `redirect` is an imaginary function that redirects the resource
  // owner's browser.
  await redirect(grant.getAuthorizationUrl(redirectUrl));

  // Another imaginary function that listens for a request to `redirectUrl`.
  var request = await listen(redirectUrl);
```
I’m not sure how I could implement these imaginary methods so I’m redirecting the user (in the current window) and when they return I’m trying restore state so I can continue. Is there a better way to do this?

Thanks

**Comment by thosakwe** [comment]
You should be fine creating another `AuthorizationCodeGrant` instance when the user returns to your app.

In `package:angel_auth_oauth2` I just have a simple `createGrant()` function. You can do the same in your app.
https://github.com/angel-dart/auth_oauth2/blob/master/lib/angel_auth_oauth2.dart#L116

The caveat, though, is that you have to call `getAuthorizationUrl` again. IMO it's kind of redundant to have to explicitly have requested a URL, but I 100% remember all the code in this package, so I'm assume there's an important reason.

**Comment by jimmyff** [comment]
Hey @thosakwe  thanks for the response. I have my redirect handling setup in a very similar way to that you've suggested. However Facebook is giving me a 400 error when the oauth library attempts to request `https://graph.facebook.com/v3.1/oauth/access_token`

The error is **OAuth "Facebook Platform" "invalid_request" "Missing redirect_uri parameter."**

It makes this request when my app calls: `await grant.handleAuthorizationResponse(params);`

I am definitely calling `getAuthorizationUrl(...)` earlier in the method and providing a redirectURL and the scopes. 

Have you seen this error before or have any suggestions to try? I'm quite stuck with it! >_<

**Comment by jonasfj** [comment]
You can't really implement a `listen` method, you can setup a handler for your redirect URL, and then... you can re-create the `grant` object in the said handler and use it to do the second part...

Here is how the `pub` client uses this:
https://github.com/dart-lang/pub/blob/ecd5b413271f2699f8cd9e23aa4eebb5030c964f/lib/src/oauth2.dart#L185-L231
