### ISSUE TITLE
Resource Owner Password Grant #

### ISSUE THREAD

**Issue by uwejan** [dart-lang/oauth2#42]
Hi, is this package supposed to work with aqueduct?
using this snippet, i get 200 on my aqueduct for both points /auth/token and http://localhost:8888/articles

but i do not know how to read the response back, tried print('$client');, i know that is wrong, because it did not work for me;
in aqueduct we could do sth like this to protect an endpoint
```
.route("/articles/[:id]")
        .link(() => Authorizer.bearer(authServer))
        .link(() => ArticlesController(context));
```
 so is it meant to work with aqueduct, and how would i get the response body.
Thank you.
```
// This URL is an endpoint that's provided by the authorization server. It's
// usually included in the server's documentation of its OAuth2 API.
final authorizationEndpoint =
    Uri.parse("http://localhost:8888/auth/token");

// The user should supply their own username and password.
final username = "example user";
final password = "example password";

// The authorization server may issue each client a separate client
// identifier and secret, which allows the server to tell which client
// is accessing it. Some servers may also have an anonymous
// identifier/secret pair that any client may use.
//
// Some servers don't require the client to authenticate itself, in which case
// these should be omitted.
final identifier = "my client identifier";
final secret = "my client secret";

// Make a request to the authorization endpoint that will produce the fully
// authenticated Client.
var client = await oauth2.resourceOwnerPasswordGrant(
    authorizationEndpoint, username, password,
    identifier: identifier, secret: secret);

// Once you have the client, you can use it just like any other HTTP client.
var result = await client.read("http://localhost:8888/articles");
```

**Comment by thosakwe** [comment]
Does your server support resource password owner grants? If you're getting an error, your server might not support that grant type.

**Comment by uwejan** [comment]
quoting from aqueduct docs, 

> The method of getting a token above - sending a username and password to /auth/token - is just one of four possible methods OAuth 2.0 uses to authenticate a user. This particular one is called the resource owner password credentials grant.

> 
https://aqueduct.io/docs/auth/what_is_oauth/
so, yes it dose support, what am facing is as described above.

**Comment by thosakwe** [comment]
Can you paste the error message you're getting?

**Comment by uwejan** [comment]
Ok;
 ```
//on aqueduct terminal i see 
[INFO] aqueduct: POST /auth/token 233ms 200   
[INFO] aqueduct: GET /articles 10ms 200
//using the snippet above;   
print(result);
Instance of 'Future<Response>'
```

**Comment by thosakwe** [comment]
I think you might be missing an `await` somewhere, so that `result` will be a `Response`, instead of `Future<Response>`.

**Comment by uwejan** [comment]
Yup, that did it, i was missing an await;
so to get this straight, using this client, whenever i do an operation with it, it will get new token from the /auth/token endpoint, right? i mean normally if a token expire in 24 hours, i would use the refresh_token to get new token, but here no need for that because it always get new token when i do a request using the client here, right?

**Comment by jonasfj** [comment]
I'm not sure if this is still relevant... But I can't answer questions on aqueduct...
