### ISSUE TITLE
How to logout?

### ISSUE THREAD

**Issue by altmnt** [dart-lang/oauth2#43]
Can I generate correct logout url somehow? Or I need to do it manually?

**Comment by thosakwe** [comment]
There's an RFC for OAuth 2.0 token revocation (I'm not sure of how widely it's been adopted, but the last update was 2013):
https://tools.ietf.org/html/rfc7009#section-2.1

It's very simple (just one `POST`, and then check for a `200`), so I don't think manually logging out will be a hassle. That's if the server you're using even follows that RFC, or has a logout endpoint whatsoever.

I'm not sure if the functionality would need to be added directly to `Client`, but if it were, I guess there would need to be a `revocationEndpoint` added to the `Client` class, which could be used to

**Comment by altmnt** [comment]
I understand that this is a simple POST but it would be nice to have that extension RFC supported (without me having to pull out the current refresh token). 
Going to close this issue though as revocation is not the part of the original rfc6749.

**Comment by thosakwe** [comment]
I think you'd have a good chance at getting a PR with support for that landed. I'm not a maintainer, though, so don't take my word for it 100%.
