### ISSUE TITLE
Custom parameters

### ISSUE THREAD

**Issue by pmaAdvensyn** [dart-lang/oauth2#44]
Is it possible to read the http response after authentication ?
I would like to get customs parameters and i can't with 
`await ouath2.resourceOwnerPasswordGrant(Uri.parse('${_url}/oauth2/token'), _username,_password, identifier: null, secret: null);`

Sample to get global_user_id parameter with my c# code 
`         Client = new RestClient(url);
            IRestRequest request = new RestRequest("oauth2/token", Method.POST);
            request.RequestFormat = DataFormat.Json;
            request.AddParameter("grant_type", "password");
            request.AddParameter("username", username);
            request.AddParameter("password", password);

            IRestResponse response = new RestResponse();
            response = Client.Execute(request);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                string json = response.Content;
                Dictionary<string, Object> dictio = JsonConvert.DeserializeObject<Dictionary<string, Object>>(json);
                Token = dictio["access_token"].ToString();
                currentUser = getGlobalUser((long)dictio["global_user_id"]);`

**Comment by thosakwe** [comment]
AFAIK this library strictly adheres to the actual OAuth2 spec, which doesn't contain an additional `global_user_id`.

You can, of course, just use the Dart `http` client manually.

**Comment by jonasfj** [comment]
Yeah, I think that would require a larger refactoring of this library... I would suggest forking it, if you want to undertake this effort :)
