### ISSUE TITLE
Change the value of basicAuth

### ISSUE THREAD

**Issue by emiltsang** [dart-lang/oauth2#50]
Is there any methods that can change the boolean value of basicAuth in AuthorizationCodeGrant().
I am using an OAuth service that does not support basic auth.

**Comment by thosakwe** [comment]
It’s a parameter in the constructor, passed by name as `basicAuth`.

**Comment by jonasfj** [comment]
```dart
final grant = AuthorizationCodeGrant(
  'my-id',
  'https://auth-url.com',
  'https://token-end-point.com',
  basicAuth: false, // <-- this is a named parameter in Dart.
);
```

Note. if anyone wants to write examples for this package, we happily accept PRs :)
