### ISSUE TITLE
Authorization Code PKCE Support

### ISSUE THREAD

**Issue by Xigtim** [dart-lang/oauth2#51]
Unless I am mistaken, I haven't seen any support for Authorization Code with PKCE. Is there any chance we see such support in the future? However, if it is already implemented, how do you use it? 

Thanks!

**Comment by EricBichara** [comment]
This would be a great addition to this library

**Comment by jonasfj** [comment]
If anyone wants to work on this I'll be happy to help with reviews.

**Comment by hadzhiyski** [comment]
Hello,
Are there any plans to release the PKCE support?

**Comment by hadzhiyski** [comment]
@jonasfj what is required to get this forward?

**Comment by jonasfj** [comment]
See review in #59

**Comment by fzyzcjy** [comment]
Hi, any updates? This would be great - since for a mobile app in Flutter, we [should](https://stackoverflow.com/questions/48819384/oauth2-flow-for-mobile-app) use the PKCE!
