### ISSUE TITLE
Client credentials grant

### ISSUE THREAD

**Issue by seanmc86** [dart-lang/oauth2#54]
Hello! 
Is there any plan to include the client credentials grant into this package at some point? It would be really helpful in order to continue using one package for all oauth2 requirements, and considering an implementation of client credentials has not yet been done for Flutter.

**Comment by jonasfj** [comment]
I don't think we have any plans to undertake such work. But if someone wants to undertake the work I'll be happy to do the review and ship it.

I think there's already some work in https://github.com/dart-lang/oauth2/pull/45

**Comment by jonasfj** [comment]
Released in version `1.5.0`, see: https://pub.dev/packages/oauth2/versions/1.5.0
