### ISSUE TITLE
Concurrent refreshCredentials issue

### ISSUE THREAD

**Issue by sm2017** [dart-lang/oauth2#62]
`refreshCredentials ` in https://github.com/dart-lang/oauth2/blob/master/lib/src/client.dart#L148 has concurrent issue , assume we have an expired access token and call `client.read` twice , `refreshCredentials` refreshed access token twice and in many OAuth server implementation , if you get access token and refresh it again , first access token will revoked (You can have only one valid access token)

We need some lock mechanism like https://pub.dev/packages/synchronized

**Comment by Kavantix** [comment]
I also ran into this.
My app did two calls in parallel at startup, so everytime that the access token was expired on startup one of the refresh calls would fail.

I have a working fix in [this branch](https://github.com/Kavantix/oauth2/tree/refreshCredentials-once) of my fork

If I have time I can make it into a PR

**Comment by lazylazyllama** [comment]
A fix for this would be really good.
