### ISSUE TITLE
Ready for production usage?

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/oauth2#74]
Hi thanks for the foundational library! I wonder whether it is mature enough to be used in production environment? Thanks!

**Comment by chrisvdb** [comment]
Also interested in the opinion of the lib author.

**Comment by sigurdm** [comment]
It is currently used in production by the pub client in the dart sdk.

That said, there are still rough edges - and we currently do not have a lot of ressources for improving this library.
