### ISSUE TITLE
How do you specify scopes?

### ISSUE THREAD

**Issue by casetofon** [dart-lang/oauth2#89]
Most APIs use a list of strings to identify which protected resources the client is requesting access to. There doesn't seem to be any way to specify that in your AuthorizationCodeGrant() method.

**Comment by casetofon** [comment]
Looking at the implementation, it seems there's a way to add the parameter to the getAuthoriztionUrl function. Maybe it should be included in the provided example so that people don't need to study the actual code.

**Comment by casetofon** [comment]
Closing

**Comment by thosakwe** [comment]
I feel like that would be an easy PR to send in?
