### ISSUE TITLE
Null-safety support

### ISSUE THREAD

**Issue by Albert221** [dart-lang/oauth2#98]
Hi! What's the status of supporting the null-safety within this package?

**Comment by Albert221** [comment]
Are you open to receive a Pull Request migrating the code to null-safety?

**Comment by Albert221** [comment]
@natebosch I'm sorry to cold-ping you like that, but I just want to make sure that this question was spotted! 

`oauth2` is crucial for our auth libraries and it would be nice to know what's the status and/or plan for the Dart Team related to this package.

I know there are currently other much more important things related to the migration than this package, so no pressure!

**Comment by Theunodb** [comment]
Would be great to get this in asap

**Comment by reinhard9921** [comment]
Will there be any assistance for this issue?

**Comment by Alecia1997** [comment]
Any update on this issue yet?

**Comment by Johann-Hagen** [comment]
Are you open te pull requests? Please, I need this package updated as it’s crucial!

**Comment by Albert221** [comment]
Looks like the code is already null-safety ready, but the `2.0.0-dev` version wasn't published to pub.dev :(

**Comment by Theunodb** [comment]
You can publish the package as prerelease so that anyone who wants to use null safety may do so.

See https://dart.dev/tools/pub/publishing#publishing-prereleases

**Comment by fzyzcjy** [comment]
This is very much needed, since today null safety becomes **stable**!

**Comment by omacranger** [comment]
Haven't had the opportunity to migrate a personal project to null-safety yet, but it seems like it should be doable using the git ref in the pubspec since they've merged in the null safety PR, no?

```yaml
dependencies:
    oauth2:
        git:
          url: git@github.com:dart-lang/oauth2.git
          ref: 9b8ee16d0dd4538173422a01532f33fc8be2548f
```

**Comment by Albert221** [comment]
It's doable only for the "end-projects", not for the packages that need a null-safe version to be published on pub.dev

**Comment by dmk-rib** [comment]
Could you publish 2.0.0-dev as a prerelease version at least?

**Comment by Arcturus5404** [comment]
Any update on this?

**Comment by Theunodb** [comment]
Also willing to help!?

**Comment by explorova** [comment]
this would be great - we are willing to help if necessary!

**Comment by natebosch** [comment]
https://pub.dev/packages/oauth2/versions/2.0.0
